version: "3.9"
   
services:
  web:
    build: .
    container_name: django-web-container
    volumes:
      # - ../db:/db
      # - ../logs:/logs
      - .:/code
    ports:
      - "8000:8000"

    environment:
      - FOO_KEY=bar_val
    command: python manage.py runserver 127.0.0.1:8000

    stdin_open: true    # docker run -i
    tty: true           # docker run -t
