version: "3.9"
   
services:
  web:
    build: .
    container_name: django-web-container
    volumes:
      - ../DBs:/sr_project_stuff/DBs
      - ../logs:/sr_project_stuff/logs
      - .:/sr_project_stuff/code
    ports:
      - "8000:8000"

    environment:
      - FOO_KEY=bar_val
      - DISA_DJ__ENV_SETTINGS_PATH=config/settings_localdev_env.sh

    env_file: ./config/settings_localdev_env.sh

    # command: python manage.py runserver 0.0.0.0:8000

    command: /bin/bash -c "python disa_app/lib/generate_browse_data_in_background.py && python manage.py runserver 0.0.0.0:8000"

    # stdin_open: true    # docker run -i
    # tty: true           # docker run -t
